server:
  port: 8002
mybatis:
  type-aliases-package: com.yuzh.springCloud.pojo
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-location: classpath:com.yuzh.springcloud.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#Spring的配置
spring:
  application:
    name: springCloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springCloud-provider-dept8002