server:
  port: 8001
mybatis:
  type-aliases-package: com.yuzh.springCloud.pojo
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-location: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#Spring的配置
spring:
  application:
    name: springCloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
#eureka
eureka:
  client:
    service-url:
      defaultZone: http:localhost:7001/eureka/